import mongoose, {Schema} from 'mongoose';
import bcrypt from "bcrypt" //To encrypt password
import jwt from "jsonwebtoken";
import crypto from "crypto";
//You can even include some logics using mongoose middlewares if needed
//eg. required, unique, trim, default values, etc.
// Schema({fields, options})
//options like timestamps gives 2 more fields createdAt and updatedAt
const userSchema = new Schema({
    avatar: {
        type: {
            url: String,
            localPath: String
        },
        default: {
            url: `https://placehold.co/200x200`,
            localPath: ``,
        }
        },
    username: {
        type: String,
        required: true,
        unique: true,
        trim: true,
        lowercase: true,
        index: true
    },
    email: {
        type: String,
        required: true,
        unique: true,
        trim: true,
        lowercase: true,
    },
    fullname: {
        type: String,
        trim: true
    },
    password: {
        type: String,
        //if someone doesn't provide password, it will throw an error with this message
        required: [true, 'Password is required']
    },
    isEmailVerified: {
        type: Boolean,
        default: false
    },
    refreshToken: {
        type: String
    },
    forgotPasswordToken: {
        type: String
    },
    forgotPasswordExpiry: {
        type: Date
    },
    emailVerificationToken: {
        type: String
    },
    emailVerificationExpiry: {
        type: Date
    }
    },{
        timestamps: true
    }
);

//Use a pre hook to do something before saving it to databaase
userSchema.pre("save", async function() {
    if (!this.isModified("password")) return;
    this.password = await bcrypt.hash(this.password, 10);
});

userSchema.methods.isPasswordCorrect = async function(password){
    return await bcrypt.compare(password, this.password)
}

userSchema.methods.generateAccessToken = function(){
    return jwt.sign({
        //auto generated by mongodb
        _id: this._id,
        email: this.email,
        username: this.username
    },
    process.env.ACCESS_TOKEN_SECRET,
    {expiresIn: process.env.ACCESS_TOKEN_EXPIRY}
)
}

userSchema.methods.generateRefreshToken = function(){
    return jwt.sign({
        //auto generated by mongodb
        _id: this._id
    },
    process.env.REFRESH_TOKEN_SECRET,
    {expiresIn: process.env.REFRESH_TOKEN_EXPIRY}
)
}

userSchema.methods.generateTemporaryToken = function(){
    const unHashedToken = crypto.randomBytes(20).toString("hex");
    const hashedToken = crypto
        .createHash("sha256")
        .update(unHashedToken)
        .digest("hex")
    const tokenExpiry = Date.now() + (20*60*1000) // 20 mins
    return {unHashedToken, hashedToken, tokenExpiry}
}


//model is used to create a collection in the database
export const User = mongoose.model('User', userSchema);